on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2  
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --force just
      - run: just check-all
